name: Build
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt update -y
          DEBIAN_FRONTEND=noninteractive sudo apt install -y build-essential gcc-aarch64-linux-gnu clang-format
      - name: Build
        env:
          CC: aarch64-linux-gnu-gcc
          FULL_CONTEXT: 0
          USE_SYSCALL_TABLE: 0
          SYSCALL_RECORD: 0
        run: |
          make clean
          make -C apps/basic clean
          make
          make -C apps/basic
      - name: Build
        env:
          CC: aarch64-linux-gnu-gcc
          FULL_CONTEXT: 1
          USE_SYSCALL_TABLE: 1
          SYSCALL_RECORD: 1
        run: |
          make clean
          make -C apps/basic clean
          make
          make -C apps/basic
      - name: Format
        run: |
          make fmt
          make -C apps/basic fmt
          test -z "$(git status --porcelain)"
